// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-FOX9rNtOrmyBvLk5BBrHMPNDKwZLYNk',
    appId: '1:919913935490:web:5ef5b05f13624a47acfa9b',
    messagingSenderId: '919913935490',
    projectId: 'notifications-59ca1',
    authDomain: 'notifications-59ca1.firebaseapp.com',
    storageBucket: 'notifications-59ca1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_abPeB1Y4ZP4SV6MA3OUHM-zLJwu0pM',
    appId: '1:919913935490:android:7f1bcfcbd8f67448acfa9b',
    messagingSenderId: '919913935490',
    projectId: 'notifications-59ca1',
    storageBucket: 'notifications-59ca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMhtDVzAz7FppzqgBV3RRoyPf7oOmX4c',
    appId: '1:919913935490:ios:4a8da820c915a167acfa9b',
    messagingSenderId: '919913935490',
    projectId: 'notifications-59ca1',
    storageBucket: 'notifications-59ca1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMhtDVzAz7FppzqgBV3RRoyPf7oOmX4c',
    appId: '1:919913935490:ios:4a8da820c915a167acfa9b',
    messagingSenderId: '919913935490',
    projectId: 'notifications-59ca1',
    storageBucket: 'notifications-59ca1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-FOX9rNtOrmyBvLk5BBrHMPNDKwZLYNk',
    appId: '1:919913935490:web:d556f4d7b84d92c8acfa9b',
    messagingSenderId: '919913935490',
    projectId: 'notifications-59ca1',
    authDomain: 'notifications-59ca1.firebaseapp.com',
    storageBucket: 'notifications-59ca1.firebasestorage.app',
  );

}